//TODO: pitää tehdä myöhemmin....
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Ella Honkanen",
    "email": "ella@gmail.com",
    "password": "ella",
    "age": 35,
    "ssn": "250187XXXXX"
}
