POST http://localhost:3001/api/datas
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVsbGFAZ21haWwuY29tIiwiaWQiOiI2M2IzZjZmMTU1ZGEwYjY2NmFmZjc0YmEiLCJpYXQiOjE2NzI3Mzg1NjYsImV4cCI6MTY3Mjc0MjE2Nn0.pXEYP3Iesc6VN8MBQQ-YtmmgJ301pzmgzlkjIaDVkVo

{
    "resultOfQuery": "Nature",
    "wantsToStudy": "Biology",
    "hobbiesAndInterests": "Thai boxing"
    //Id:n tulla saada kirjautuneelta käyttäjältä
}
